name: Dart

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup Dart
        uses: subosito/dart-action@v2
        with:
          flutter-version: '3.13.9'
      - name: Get dependencies
        run: dart pub get
      - name: Run analyzer
        run: dart analyze
      - name: Run tests
        run: dart test
