name: Dart

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          channel: 'stable'
      - name: Get dependencies
        working-directory: my_app
        run: flutter pub get
      - name: Run analyzer
        working-directory: my_app
        run: flutter analyze
      - name: Run tests
        working-directory: my_app
        run: flutter test
